on: [push]
jobs:
  docs:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y doxygen python3-pip
          pip3 install esp-doxybook
      - name: Generate API.md
        run: |
          doxygen
          esp-doxybook -i docs/xml -o API.md
