on: [push]
jobs:
  docs:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y doxygen pipx
          pipx install esp-doxybook
      - name: Generate API.md
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          doxygen
          esp-doxybook -i docs/xml -o API.md
