on: [push]
jobs:
  examples:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc make cmake
      - name: Configure
        run: cmake -B build -DRID_BUILD_EXAMPLES=ON
      - name: Build
        run: cmake --build build
      - name: Run examples
        run: |
          cd build/examples
          ./example_basic_id
          ./example_location
          ./example_self_id
          ./example_system
          ./example_operator_id
          ./example_message
          ./example_message_pack
          ./example_json
          ./example_auth_page
          ./example_validate
          ./rid_cli --decode 12202d3e0420bd5c25401c190d0000c10834084a0339300100
