on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc make
      - name: Run unit tests
        run: |
          cd tests
          make clean
          make test
