on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc make cmake
      - name: Configure
        run: cmake -B build -DRID_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure --verbose
