on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc make cmake
      - name: Configure
        run: cmake -B build -DRID_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure --verbose
      - name: Configure with RID_DISABLE_JSON
        run: cmake -B build-nojson -DRID_BUILD_TESTS=ON -DRID_DISABLE_JSON=ON
      - name: Test with RID_DISABLE_JSON
        run: cmake --build build-nojson
      - name: Test without JSON
        run: cd build-nojson && ctest --output-on-failure --verbose
