on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc make cmake
      - name: Run unit tests
        run: |
          mkdir build
          cd build
          cmake -DRID_BUILD_TESTS=ON ..
          make
          ctest --output-on-failure
